---
- hosts: all
  become: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: Install the package "python-software-properties"
      apt:
        name: python-software-properties
        state: present

    - apt_repository:
        repo: 'ppa:openjdk-r/ppa'

    - name: Update repositories cache and install "Java OpenJDK7" package
      apt:
        name: openjdk-7-jdk
        update_cache: yes

    - apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Update repositories cache and install "Jenkins" package
      apt:
        name: jenkins
        update_cache: yes

    - name: Update repositories cache and install "Nginx" package
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: delete default nginx configs
      file: 
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Copy files from foo to bar
      copy: remote_src=True src=/vagrant/nginx_jenkins dest=/etc/nginx/sites-available/jenkins

    - name: Create Nginx config symbolic link to Nginx
      file:
        src: /etc/nginx/sites-available/jenkins
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        state: link

    - name: restart jenkins service
      systemd:
        state: restarted
        name: jenkins

    - name: restart nginx service
      systemd:
        state: restarted
        name: nginx